"""Obsidian file I/O and Markdown post-processing module.

Handles output sanitization (stripping hallucinated outer markdown fences),
safe YAML frontmatter title extraction, filename sanitization, and
non-destructive vault write collision handling.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Optional

import yaml
from rich.console import Console

console = Console()
err_console = Console(stderr=True)


class ObsidianIOError(Exception):
    """Base exception for Obsidian file operations."""


def sanitize_llm_output(raw_output: str) -> str:
    """Strip hallucinated outer markdown code fences from the LLM output.

    Local models frequently wrap the entire generated note in ```markdown ... ```
    code blocks. This sanitizer removes the outer fences while preserving all
    internal code blocks (such as LaTeX or python snippets) so that YAML
    frontmatter sits cleanly on line 1.

    Args:
        raw_output: The raw text generated by the LLM.

    Returns:
        Cleaned markdown content starting with YAML frontmatter or heading.
    """
    content = raw_output.strip()

    # Pattern matching outer ```markdown or ``` fences wrapping the entire output
    outer_fence_pattern = re.compile(
        r"^```(?:markdown|md)?\s*\n(.*)\n```\s*$",
        re.DOTALL | re.IGNORECASE,
    )

    match = outer_fence_pattern.match(content)
    if match:
        return match.group(1).strip()

    # In case there is an unclosed leading fence at line 1
    content = re.sub(r"^```(?:markdown|md)?\s*\n", "", content, flags=re.IGNORECASE)
    return content.strip()


def sanitize_filename(name: str, max_length: int = 200) -> str:
    """Sanitize a string into a safe, valid filesystem filename.

    Removes or replaces illegal OS characters: / \\ : * ? " < > |
    Trims trailing dots and spaces, and guarantees a .md extension.

    Args:
        name: Desired filename or title string.
        max_length: Maximum allowed character length for the filename stem.

    Returns:
        A sanitized filename ending with '.md'.
    """
    cleaned = name.strip()

    # Replace colons and slashes with clean separators
    cleaned = re.sub(r"\s*[/\\:]\s*", " - ", cleaned)

    # Remove invalid characters for Windows, macOS, and Linux
    cleaned = re.sub(r'[<>"|?*\x00-\x1f]', "", cleaned)

    # Collapse multiple consecutive dashes or spaces
    cleaned = re.sub(r"\s+", " ", cleaned)
    cleaned = re.sub(r"-+", "-", cleaned)
    cleaned = cleaned.strip(". -")

    if not cleaned:
        cleaned = "Untitled Note"

    # Truncate length if needed
    if len(cleaned) > max_length:
        cleaned = cleaned[:max_length].rstrip(". -")

    if not cleaned.endswith(".md"):
        cleaned = f"{cleaned}.md"

    return cleaned


def extract_note_title(content: str, fallback_title: str = "Lecture-Note") -> str:
    """Safely extract the note title from YAML frontmatter or Markdown H1.

    Falls back gracefully if YAML parsing fails or if title is absent.

    Args:
        content: The cleaned Markdown note text.
        fallback_title: Fallback string if no title can be extracted.

    Returns:
        A clean title string.
    """
    # 1. Try extracting from YAML frontmatter
    frontmatter_match = re.match(r"^---\s*\n(.*?)\n---\s*(?:\n|$)", content, re.DOTALL)
    if frontmatter_match:
        yaml_text = frontmatter_match.group(1)
        try:
            parsed_yaml = yaml.safe_load(yaml_text)
            if isinstance(parsed_yaml, dict):
                title = parsed_yaml.get("title")
                if title and isinstance(title, str) and title.strip():
                    return title.strip()
        except Exception:
            # YAML parsing failed (malformed YAML); fall through to H1 search
            pass

    # 2. Fallback: Search for the first Markdown H1 header (# Title)
    h1_match = re.search(r"^#\s+(.+)$", content, re.MULTILINE)
    if h1_match and h1_match.group(1).strip():
        return h1_match.group(1).strip()

    return fallback_title


def resolve_collision_path(vault_path: Path, desired_filename: str) -> Path:
    """Determine a non-destructive destination file path.

    If the file already exists in the vault, appends an incremented counter
    e.g., 'Calculus - SVD (1).md', 'Calculus - SVD (2).md' to prevent data loss.

    Args:
        vault_path: Target directory inside the Obsidian vault.
        desired_filename: The target filename (e.g., 'Linear Algebra.md').

    Returns:
        An available Path in the vault that does not collide with existing files.
    """
    sanitized = sanitize_filename(desired_filename)
    target_path = vault_path / sanitized

    if not target_path.exists():
        return target_path

    # Extract base stem and extension
    stem = target_path.stem
    suffix = target_path.suffix

    counter = 1
    while True:
        candidate_name = f"{stem} ({counter}){suffix}"
        candidate_path = vault_path / candidate_name
        if not candidate_path.exists():
            return candidate_path
        counter += 1


def write_note_to_vault(
    vault_path: Path,
    content: str,
    desired_filename: Optional[str] = None,
    fallback_title: str = "Lecture-Note",
    overwrite: bool = False,
) -> Path:
    """Save the generated note content safely to the Obsidian vault.

    Args:
        vault_path: Target Obsidian vault folder.
        content: The cleaned Markdown note content.
        desired_filename: Optional explicit filename. If None, derived from content title.
        fallback_title: Fallback title if extraction fails.
        overwrite: If True, overwrites existing file; otherwise resolves collision.

    Returns:
        Absolute Path to the written note file in the vault.

    Raises:
        ObsidianIOError: If writing to the vault directory fails.
    """
    resolved_vault = vault_path.resolve()
    if not resolved_vault.exists():
        raise ObsidianIOError(f"Obsidian vault directory does not exist: {resolved_vault}")
    if not resolved_vault.is_dir():
        raise ObsidianIOError(f"Obsidian vault path is not a directory: {resolved_vault}")

    # Determine filename
    if desired_filename:
        filename = sanitize_filename(desired_filename)
    else:
        title = extract_note_title(content, fallback_title=fallback_title)
        filename = sanitize_filename(title)

    # Resolve collision
    if overwrite:
        target_path = resolved_vault / filename
    else:
        target_path = resolve_collision_path(resolved_vault, filename)

    try:
        target_path.write_text(content, encoding="utf-8")
    except Exception as exc:
        raise ObsidianIOError(f"Failed to write note to {target_path}: {exc}") from exc

    return target_path
